import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { QueryProvider } from './providers/QueryProvider';
import { Toaster } from "@/components/ui/sonner"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hive Africa | Courses ",
  description: "Generated by Analytix Hive",
  icons: {
    icon: "/assets/Analytix Hive Logo 3.png",
    // shortcut: "/favicon.ico",
    // apple: "/apple-touch-icon.png",
  },
};
// Create a client


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">
   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


        
        <QueryProvider>
          <Toaster/>
        {children}
        </QueryProvider>
       
      </body>
     
    </html>
  );
}
